-- CreateEnum
CREATE TYPE "FreightType" AS ENUM ('DIRECTION_AND_CATEGORY', 'DIRECTION_AND_DELIVERY_FEE', 'DISTANCE_BASED');

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "freightType" "FreightType" NOT NULL DEFAULT 'DIRECTION_AND_CATEGORY',
ADD COLUMN     "pricePerDelivery" DOUBLE PRECISION,
ADD COLUMN     "pricePerKm" DOUBLE PRECISION;
